-- MARCADOR DE PERSONAL MUNSTER
-- Ejecutar una sola vez en Supabase > SQL Editor.

create extension if not exists pgcrypto with schema extensions;

alter table public.registros_horarios
  add column if not exists origen text not null default 'manual',
  add column if not exists estado_marcacion text not null default 'finalizada';

alter table public.registros_horarios
  alter column cargado_por drop not null;

do $$ begin
  alter table public.registros_horarios add constraint registros_origen_check
    check (origen in ('manual','marcador','correccion'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.registros_horarios add constraint registros_estado_marcacion_check
    check (estado_marcacion in ('trabajando','en_corte','segundo_tramo','finalizada'));
exception when duplicate_object then null; end $$;

create table if not exists public.credenciales_fichaje (
  moza_id bigint primary key references public.mozas(id) on delete cascade,
  pin_hash text not null,
  intentos_fallidos integer not null default 0,
  bloqueado_hasta timestamptz,
  actualizado_el timestamptz not null default now(),
  actualizado_por uuid references auth.users(id)
);

create table if not exists public.dispositivos_fichaje (
  id bigint generated by default as identity primary key,
  nombre text not null,
  token_hash bytea not null unique,
  activo boolean not null default true,
  creado_el timestamptz not null default now(),
  creado_por uuid references auth.users(id),
  ultimo_uso timestamptz
);

create table if not exists public.codigos_activacion_fichaje (
  id bigint generated by default as identity primary key,
  nombre_dispositivo text not null,
  codigo_hash bytea not null unique,
  vence_el timestamptz not null,
  usado_el timestamptz,
  creado_el timestamptz not null default now(),
  creado_por uuid references auth.users(id)
);

create table if not exists public.marcaciones_fichaje (
  id bigint generated by default as identity primary key,
  moza_id bigint references public.mozas(id),
  registro_id bigint references public.registros_horarios(id) on delete set null,
  dispositivo_id bigint references public.dispositivos_fichaje(id),
  fecha_hora timestamptz not null default now(),
  accion text not null check (accion in ('entrada','salida','salida_corte','regreso')),
  resultado text not null check (resultado in ('aceptada','rechazada')),
  detalle text
);

alter table public.credenciales_fichaje enable row level security;
alter table public.dispositivos_fichaje enable row level security;
alter table public.codigos_activacion_fichaje enable row level security;
alter table public.marcaciones_fichaje enable row level security;

revoke all on public.credenciales_fichaje from anon, authenticated;
revoke all on public.dispositivos_fichaje from anon, authenticated;
revoke all on public.codigos_activacion_fichaje from anon, authenticated;
revoke all on public.marcaciones_fichaje from anon, authenticated;

create or replace function public.minutos_entre(p_entrada time, p_salida time)
returns integer language sql immutable as $$
  select case when p_entrada is null or p_salida is null then 0
    else (extract(epoch from (p_salida - p_entrada))::integer / 60 +
      case when p_salida < p_entrada then 1440 else 0 end)
  end;
$$;

create or replace function public.actualizar_pin_moza(p_moza_id bigint, p_pin text)
returns boolean language plpgsql security definer set search_path=public,extensions as $$
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;
  if p_pin !~ '^[0-9]{4,6}$' then raise exception 'El PIN debe tener entre 4 y 6 números'; end if;
  if not exists(select 1 from public.mozas where id=p_moza_id and activa=true) then raise exception 'Moza no encontrada'; end if;
  insert into public.credenciales_fichaje(moza_id,pin_hash,actualizado_por)
  values(p_moza_id,extensions.crypt(p_pin,extensions.gen_salt('bf')),auth.uid())
  on conflict(moza_id) do update set pin_hash=excluded.pin_hash,intentos_fallidos=0,
    bloqueado_hasta=null,actualizado_el=now(),actualizado_por=auth.uid();
  return true;
end; $$;

create or replace function public.crear_codigo_activacion(p_nombre text default 'Computadora Munster')
returns table(codigo text, vence_el timestamptz) language plpgsql security definer set search_path=public,extensions as $$
declare v_codigo text;
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;
  v_codigo := 'MUN-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));
  insert into public.codigos_activacion_fichaje(nombre_dispositivo,codigo_hash,vence_el,creado_por)
  values(coalesce(nullif(trim(p_nombre),''),'Computadora Munster'),extensions.digest(v_codigo,'sha256'),now()+interval '15 minutes',auth.uid());
  return query select v_codigo,now()+interval '15 minutes';
end; $$;

create or replace function public.activar_dispositivo_fichaje(p_codigo text)
returns jsonb language plpgsql security definer set search_path=public,extensions as $$
declare v_codigo public.codigos_activacion_fichaje%rowtype; v_token text; v_id bigint;
begin
  select * into v_codigo from public.codigos_activacion_fichaje
  where codigo_hash=extensions.digest(upper(trim(p_codigo)),'sha256') and usado_el is null and vence_el>now()
  for update;
  if not found then return jsonb_build_object('ok',false,'mensaje','Código incorrecto o vencido'); end if;
  v_token := replace(gen_random_uuid()::text,'-','') || replace(gen_random_uuid()::text,'-','');
  insert into public.dispositivos_fichaje(nombre,token_hash,creado_por)
  values(v_codigo.nombre_dispositivo,extensions.digest(v_token,'sha256'),v_codigo.creado_por) returning id into v_id;
  update public.codigos_activacion_fichaje set usado_el=now() where id=v_codigo.id;
  return jsonb_build_object('ok',true,'token',v_token,'dispositivo_id',v_id);
end; $$;

create or replace function public.validar_dispositivo_fichaje(p_token text)
returns boolean language plpgsql security definer set search_path=public,extensions as $$
begin
  update public.dispositivos_fichaje set ultimo_uso=now()
  where token_hash=extensions.digest(p_token,'sha256') and activo=true;
  return found;
end; $$;

create or replace function public.listar_mozas_fichaje(p_token text)
returns table(moza_id bigint,nombre text,estado text) language plpgsql security definer set search_path=public,extensions as $$
declare v_hoy date := (now() at time zone 'America/Argentina/Catamarca')::date;
begin
  if not exists(select 1 from public.dispositivos_fichaje where token_hash=extensions.digest(p_token,'sha256') and activo=true)
    then raise exception 'Computadora no autorizada'; end if;
  return query
  select m.id,m.nombre,coalesce(r.estado_marcacion,'sin_entrada')
  from public.mozas m
  left join lateral (
    select rh.estado_marcacion from public.registros_horarios rh
    where rh.moza_id=m.id and
      (rh.fecha=v_hoy or (rh.fecha=v_hoy-1 and rh.estado_marcacion in ('trabajando','en_corte','segundo_tramo')))
    order by case when rh.estado_marcacion in ('trabajando','en_corte','segundo_tramo') then 0 else 1 end,rh.fecha desc limit 1
  ) r on true where m.activa=true order by m.id;
end; $$;

create or replace function public.marcar_fichaje(p_token text,p_moza_id bigint,p_pin text,p_accion text)
returns jsonb language plpgsql security definer set search_path=public,extensions as $$
declare
  v_device public.dispositivos_fichaje%rowtype; v_cred public.credenciales_fichaje%rowtype;
  v_reg public.registros_horarios%rowtype; v_hoy date := (now() at time zone 'America/Argentina/Catamarca')::date;
  v_hora time := (now() at time zone 'America/Argentina/Catamarca')::time(0); v_min integer; v_msg text;
begin
  select * into v_device from public.dispositivos_fichaje where token_hash=extensions.digest(p_token,'sha256') and activo=true;
  if not found then return jsonb_build_object('ok',false,'mensaje','Computadora no autorizada'); end if;
  if p_accion not in ('entrada','salida','salida_corte','regreso') then return jsonb_build_object('ok',false,'mensaje','Acción inválida'); end if;
  select * into v_cred from public.credenciales_fichaje where moza_id=p_moza_id for update;
  if not found then return jsonb_build_object('ok',false,'mensaje','Todavía no tenés un PIN configurado'); end if;
  if v_cred.bloqueado_hasta is not null and v_cred.bloqueado_hasta>now() then
    return jsonb_build_object('ok',false,'mensaje','PIN bloqueado temporalmente. Avisá a una encargada');
  end if;
  if v_cred.bloqueado_hasta is not null and v_cred.bloqueado_hasta<=now() then
    update public.credenciales_fichaje set intentos_fallidos=0,bloqueado_hasta=null where moza_id=p_moza_id;
    v_cred.intentos_fallidos:=0; v_cred.bloqueado_hasta:=null;
  end if;
  if extensions.crypt(p_pin,v_cred.pin_hash)<>v_cred.pin_hash then
    update public.credenciales_fichaje set intentos_fallidos=intentos_fallidos+1,
      bloqueado_hasta=case when intentos_fallidos+1>=5 then now()+interval '10 minutes' else null end where moza_id=p_moza_id;
    insert into public.marcaciones_fichaje(moza_id,dispositivo_id,accion,resultado,detalle)
      values(p_moza_id,v_device.id,p_accion,'rechazada','PIN incorrecto');
    return jsonb_build_object('ok',false,'mensaje','PIN incorrecto');
  end if;
  update public.credenciales_fichaje set intentos_fallidos=0,bloqueado_hasta=null where moza_id=p_moza_id;

  select * into v_reg from public.registros_horarios where moza_id=p_moza_id and
    (fecha=v_hoy or (fecha=v_hoy-1 and estado_marcacion in ('trabajando','en_corte','segundo_tramo')))
    order by case when estado_marcacion in ('trabajando','en_corte','segundo_tramo') then 0 else 1 end,fecha desc limit 1 for update;

  if p_accion='entrada' then
    if found then return jsonb_build_object('ok',false,'mensaje',case when v_reg.estado_marcacion='finalizada' then 'La jornada de hoy ya fue finalizada' else 'Ya tenés una entrada marcada' end); end if;
    insert into public.registros_horarios(moza_id,fecha,estado_dia,entrada_1,salida_1,entrada_2,salida_2,minutos_trabajados,observacion,cargado_por,modificado_el,origen,estado_marcacion)
    values(p_moza_id,v_hoy,'trabajo',v_hora,null,null,null,0,'Marcación automática',null,now(),'marcador','trabajando') returning * into v_reg;
    v_msg:='Entrada registrada a las '||to_char(v_hora,'HH24:MI');
  elsif not found then return jsonb_build_object('ok',false,'mensaje','No hay una entrada pendiente');
  elsif p_accion='salida_corte' and v_reg.estado_marcacion='trabajando' then
    v_min:=public.minutos_entre(v_reg.entrada_1,v_hora);
    update public.registros_horarios set salida_1=v_hora,minutos_trabajados=v_min,estado_marcacion='en_corte',modificado_el=now() where id=v_reg.id returning * into v_reg;
    v_msg:='Salida al corte registrada a las '||to_char(v_hora,'HH24:MI');
  elsif p_accion='regreso' and v_reg.estado_marcacion='en_corte' then
    update public.registros_horarios set entrada_2=v_hora,estado_marcacion='segundo_tramo',modificado_el=now() where id=v_reg.id returning * into v_reg;
    v_msg:='Regreso registrado a las '||to_char(v_hora,'HH24:MI');
  elsif p_accion='salida' and v_reg.estado_marcacion in ('trabajando','segundo_tramo') then
    if v_reg.estado_marcacion='trabajando' then
      v_min:=public.minutos_entre(v_reg.entrada_1,v_hora);
      update public.registros_horarios set salida_1=v_hora,minutos_trabajados=v_min,estado_marcacion='finalizada',modificado_el=now() where id=v_reg.id returning * into v_reg;
    else
      v_min:=public.minutos_entre(v_reg.entrada_1,v_reg.salida_1)+public.minutos_entre(v_reg.entrada_2,v_hora);
      update public.registros_horarios set salida_2=v_hora,minutos_trabajados=v_min,estado_marcacion='finalizada',modificado_el=now() where id=v_reg.id returning * into v_reg;
    end if;
    v_msg:='Salida registrada a las '||to_char(v_hora,'HH24:MI');
  else return jsonb_build_object('ok',false,'mensaje','Esa marcación no corresponde al estado actual');
  end if;
  insert into public.marcaciones_fichaje(moza_id,registro_id,dispositivo_id,accion,resultado,detalle)
    values(p_moza_id,v_reg.id,v_device.id,p_accion,'aceptada',v_msg);
  update public.dispositivos_fichaje set ultimo_uso=now() where id=v_device.id;
  return jsonb_build_object('ok',true,'mensaje',v_msg);
end; $$;

revoke all on function public.actualizar_pin_moza(bigint,text) from public;
revoke all on function public.crear_codigo_activacion(text) from public;
revoke all on function public.activar_dispositivo_fichaje(text) from public;
revoke all on function public.validar_dispositivo_fichaje(text) from public;
revoke all on function public.listar_mozas_fichaje(text) from public;
revoke all on function public.marcar_fichaje(text,bigint,text,text) from public;
grant execute on function public.actualizar_pin_moza(bigint,text) to authenticated;
grant execute on function public.crear_codigo_activacion(text) to authenticated;
grant execute on function public.activar_dispositivo_fichaje(text) to anon,authenticated;
grant execute on function public.validar_dispositivo_fichaje(text) to anon,authenticated;
grant execute on function public.listar_mozas_fichaje(text) to anon,authenticated;
grant execute on function public.marcar_fichaje(text,bigint,text,text) to anon,authenticated;
