import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";

const cfg=window.MUNSTER_CONFIG||{},configured=cfg.supabaseKey&&!cfg.supabaseKey.includes("PEGAR_AQUI");
const supabase=configured?createClient(cfg.supabaseUrl,cfg.supabaseKey):null;
const $=id=>document.getElementById(id),localIso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`,today=()=>localIso(new Date());
const fmtDate=s=>new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"UTC"}).format(new Date(`${s}T12:00:00Z`));
const fmtMin=(n,signed=false)=>{const sign=n<0?"−":signed&&n>0?"+":"",v=Math.abs(n),h=Math.floor(v/60),m=v%60;return v?`${sign}${h?`${h} h`:""}${h&&m?" ":""}${m?`${m} min`:""}`:"0 h"};
const minBetween=(a,b)=>{if(!a||!b)return 0;const[ah,am]=a.split(":").map(Number),[bh,bm]=b.split(":").map(Number);let v=bh*60+bm-ah*60-am;if(v<0)v+=1440;return v};
const weekDates=()=>{const d=new Date(),start=new Date(d),daysSinceMonday=(d.getDay()+6)%7;start.setDate(d.getDate()-daysSinceMonday);const end=new Date(start);end.setDate(start.getDate()+6);return[localIso(start),localIso(end)]};
let state={user:null,mozas:[],week:null,expected:[],entries:[],movements:[],viewDate:today()};
function toast(message,error=false){const t=$("toast");t.textContent=message;t.className=`toast ${error?"bad":""}`;setTimeout(()=>t.classList.add("hidden"),2400)}
function showLogin(message=""){ $("login").classList.remove("hidden");$("app").classList.add("hidden");$("login-error").textContent=message;if(!configured)$("login-error").textContent="Falta conectar la clave publicable de Supabase." }
function showApp(){ $("login").classList.add("hidden");$("app").classList.remove("hidden");$("user-letter").textContent=(state.user.email||"N")[0].toUpperCase() }
async function load(){const[start,end]=weekDates();let{data:week,error}=await supabase.from("semanas").select("*").eq("fecha_inicio",start).maybeSingle();if(error)throw error;if(!week){({data:week,error}=await supabase.from("semanas").insert({fecha_inicio:start,fecha_fin:end}).select().single());if(error)throw error;const{data:people,error:peopleError}=await supabase.from("mozas").select("id").eq("activa",true);if(peopleError)throw peopleError;const{error:defaultsError}=await supabase.from("horas_esperadas").insert(people.map(m=>({semana_id:week.id,moza_id:m.id,minutos_esperados:2400,cantidad_francos:2})));if(defaultsError)throw defaultsError}state.week=week;
 const [m,e,r,mv]=await Promise.all([supabase.from("mozas").select("*").eq("activa",true).order("id"),supabase.from("horas_esperadas").select("*").eq("semana_id",week.id),supabase.from("registros_horarios").select("*").gte("fecha",start).lte("fecha",end),supabase.from("movimientos_horas").select("*").order("fecha")]);
 for(const x of[m,e,r,mv])if(x.error)throw x.error;state.mozas=m.data;state.expected=e.data;state.entries=r.data;state.movements=mv.data;render()}
function expected(id){return state.expected.find(x=>x.moza_id===id)?.minutos_esperados??2400} function worked(id){return state.entries.filter(x=>x.moza_id===id).reduce((a,x)=>a+x.minutos_trabajados,0)} function balance(id){return state.movements.filter(x=>x.moza_id===id).reduce((a,x)=>a+x.minutos,0)}
function render(){showApp();$("week-label").textContent=`${fmtDate(state.week.fecha_inicio)} al ${fmtDate(state.week.fecha_fin)}`;$("week-status").textContent=state.week.estado.toUpperCase();$("view-date").value=state.viewDate;$("today-label").textContent=`${state.viewDate===today()?"HOY":"FECHA"} · ${fmtDate(state.viewDate)}`;const todays=state.entries.filter(x=>x.fecha===state.viewDate);$("daily-count").textContent=`${todays.length} de ${state.mozas.length} definidas`;
 $("daily-list").innerHTML=state.mozas.map(m=>{const e=todays.find(x=>x.moza_id===m.id),workedDay=e?.estado_dia==='trabajo'||!e?.estado_dia;return`<article class="employee-card"><div class="avatar">${m.nombre[0]}</div><div class="employee-info"><h4>${m.nombre}</h4>${e?(workedDay?`<p>${e.entrada_1.slice(0,5)}–${e.salida_1.slice(0,5)}${e.entrada_2?` / ${e.entrada_2.slice(0,5)}–${e.salida_2.slice(0,5)}`:""}</p><strong>${fmtMin(e.minutos_trabajados)} trabajadas</strong>`:`<p class="day-state">${e.estado_dia}</p>`):`<p class="muted">Sin definir</p>`}</div><button class="edit-btn ${e?"done":""}" data-entry="${m.id}">${e?"Editar":"Cargar"}</button></article>`}).join("");
 $("weekly-list").innerHTML=state.mozas.map(m=>{const diff=worked(m.id)-expected(m.id),open=state.week.estado==='abierta',label=open?(diff<0?'Restan registrar':'Excedente provisorio'):(diff>0?'Horas extra':diff<0?'Horas faltantes':'Diferencia'),display=open&&diff<0?fmtMin(Math.abs(diff)):fmtMin(diff,true),options=[0,8,16,24,32,40,48].map(h=>`<option value="${h*60}" ${expected(m.id)===h*60?'selected':''}>${h} h${h===0?' · Vacaciones':h===40?' · 2 francos':h===48?' · 1 franco':''}</option>`).join('');return`<article class="summary-row"><div class="avatar small">${m.nombre[0]}</div><div class="summary-name"><h4>${m.nombre}</h4><p>${state.entries.filter(x=>x.moza_id===m.id).length} días definidos</p></div><label>Esperadas<select data-expected="${m.id}" ${state.week.estado==='cerrada'?'disabled':''}>${options}</select></label><div class="metric"><span>Realizadas</span><strong>${fmtMin(worked(m.id))}</strong></div><div class="difference ${!open&&diff>0?'positive':!open&&diff<0?'negative':''}"><span>${label}</span><strong>${display}</strong></div></article>`}).join("");
 $("close-week").disabled=state.week.estado==="cerrada";$("close-week").textContent=state.week.estado==="cerrada"?"✓ Semana cerrada":"Cerrar semana y confirmar diferencias";
 $("balance-list").innerHTML=state.mozas.map(m=>{const b=balance(m.id),status=b===0?'AL DÍA':b>0?'PENDIENTE':'HORAS FALTANTES',message=b===0?'No se deben horas':b>0?fmtMin(b):`${fmtMin(Math.abs(b))} faltantes`;return`<article class="balance-card ${b===0?'settled':''}"><div class="balance-top"><div class="avatar">${m.nombre[0]}</div><span class="status">${status}</span></div><h4>${m.nombre}</h4><strong>${message}</strong><button data-return="${m.id}" ${b<=0?'disabled':''}>Registrar devolución</button></article>`}).join("");$("report-employee").innerHTML=state.mozas.map(m=>`<option value="${m.id}">${m.nombre}</option>`).join("");if(!$("report-month").value)$("report-month").value=today().slice(0,7);if(!$("delete-month").value){const d=new Date();d.setMonth(d.getMonth()-1);$("delete-month").value=localIso(d).slice(0,7)}bindDynamic()}
function bindDynamic(){document.querySelectorAll("[data-entry]").forEach(b=>b.onclick=()=>openEntry(Number(b.dataset.entry)));document.querySelectorAll("[data-return]").forEach(b=>b.onclick=()=>openReturn(Number(b.dataset.return)));document.querySelectorAll("[data-expected]").forEach(s=>s.onchange=()=>saveExpected(Number(s.dataset.expected),Number(s.value)))}
function openEntry(id){const m=state.mozas.find(x=>x.id===id),e=state.entries.find(x=>x.moza_id===id&&x.fecha===state.viewDate),status=e?.estado_dia||"trabajo";$("entry-name").textContent=m.nombre;$("entry-moza").value=id;$("entry-date").value=e?.fecha||state.viewDate;$("day-status").value=status;$("start1").value=e?.entrada_1?.slice(0,5)||"07:00";$("end1").value=e?.salida_1?.slice(0,5)||"15:00";$("split").checked=Boolean(e?.entrada_2);$("start2").value=e?.entrada_2?.slice(0,5)||"20:00";$("end2").value=e?.salida_2?.slice(0,5)||"00:00";$("entry-note").value=e?.observacion||"";$("work-fields").classList.toggle("hidden",status!=="trabajo");$("split-fields").classList.toggle("hidden",!$("split").checked);$("entry-dialog").showModal()}
function openReturn(id){const m=state.mozas.find(x=>x.id===id);$("return-name").textContent=m.nombre;$("return-moza").value=id;$("return-balance").textContent=fmtMin(balance(id));$("return-dialog").showModal()}
async function saveExpected(id,minutes){const{error}=await supabase.from("horas_esperadas").upsert({semana_id:state.week.id,moza_id:id,minutos_esperados:minutes,cantidad_francos:minutes===2400?2:minutes===2880?1:null},{onConflict:"semana_id,moza_id"});if(error)return toast(error.message,true);await load();toast("Horas esperadas guardadas")}
async function closeWeek(){const defined=new Map(state.mozas.map(m=>[m.id,state.entries.filter(e=>e.moza_id===m.id).length])),pending=state.mozas.filter(m=>defined.get(m.id)<5);if(pending.length){const names=pending.map(m=>`${m.nombre} (${defined.get(m.id)} días definidos)`).join("\n");if(!confirm(`Atención: faltan días por definir.\n\n${names}\n\nLos francos también deben marcarse. ¿Cerrar igualmente?`))return}if(!confirm("¿Confirmar el cierre? Las diferencias pasarán al banco de horas y ya no podrán editarse desde el resumen."))return;const rows=state.mozas.map(m=>({moza_id:m.id,semana_id:state.week.id,fecha:state.week.fecha_fin,minutos:worked(m.id)-expected(m.id),tipo:"diferencia_semanal",observacion:`Semana ${state.week.fecha_inicio} al ${state.week.fecha_fin}`,cargado_por:state.user.id}));let{error}=await supabase.from("movimientos_horas").delete().eq("semana_id",state.week.id).eq("tipo","diferencia_semanal");if(!error)({error}=await supabase.from("movimientos_horas").insert(rows));if(!error)({error}=await supabase.from("semanas").update({estado:"cerrada",cerrada_el:new Date().toISOString(),cerrada_por:state.user.id}).eq("id",state.week.id));if(error)return toast(error.message,true);await load();toast("Semana cerrada")}
$("login-form").onsubmit=async e=>{e.preventDefault();if(!configured)return showLogin();const{data,error}=await supabase.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(error)return showLogin("Correo o contraseña incorrectos");state.user=data.user;await load()};
$("logout").onclick=async()=>{await supabase.auth.signOut();state.user=null;showLogin()};document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".tab-panel").forEach(x=>x.classList.toggle("hidden",x.id!==b.dataset.tab))});
$("split").onchange=()=>$("split-fields").classList.toggle("hidden",!$("split").checked);$("day-status").onchange=()=>$("work-fields").classList.toggle("hidden",$("day-status").value!=="trabajo");$("entry-form").onsubmit=async e=>{e.preventDefault();const status=$("day-status").value,works=status==="trabajo",split=works&&$("split").checked,minutes=works?minBetween($("start1").value,$("end1").value)+(split?minBetween($("start2").value,$("end2").value):0):0,row={moza_id:Number($("entry-moza").value),fecha:$("entry-date").value,estado_dia:status,entrada_1:works?$("start1").value:"00:00",salida_1:works?$("end1").value:"00:00",entrada_2:split?$("start2").value:null,salida_2:split?$("end2").value:null,minutos_trabajados:minutes,observacion:$("entry-note").value,cargado_por:state.user.id,modificado_el:new Date().toISOString()};const{error}=await supabase.from("registros_horarios").upsert(row,{onConflict:"moza_id,fecha"});if(error)return toast(error.message,true);state.viewDate=row.fecha;$("entry-dialog").close();await load();toast("Día guardado")};
$("return-form").onsubmit=async e=>{e.preventDefault();const id=Number($("return-moza").value),minutes=Number($("return-hours").value)*60+Number($("return-minutes").value);if(minutes<=0||minutes>balance(id))return toast("Revisá la cantidad a devolver",true);const{error}=await supabase.from("movimientos_horas").insert({moza_id:id,semana_id:state.week.id,fecha:today(),minutos:-minutes,tipo:"devolucion",modalidad:$("return-note").value,cargado_por:state.user.id});if(error)return toast(error.message,true);$("return-dialog").close();await load();toast("Devolución registrada")};$("close-week").onclick=closeWeek;
function moveDay(delta){const d=new Date(`${state.viewDate}T12:00:00`);d.setDate(d.getDate()+delta);state.viewDate=localIso(d);render()}$("prev-day").onclick=()=>moveDay(-1);$("next-day").onclick=()=>moveDay(1);$("today-btn").onclick=()=>{state.viewDate=today();render()};$("view-date").onchange=e=>{state.viewDate=e.target.value;render()};
$("report-period").onchange=()=>$("report-month-wrap").classList.toggle("hidden",$("report-period").value!=="month");$("report-type").onchange=()=>$("report-employee-wrap").classList.toggle("hidden",$("report-type").value!=="individual");
async function reportData(){const monthly=$("report-period").value==="month",month=$("report-month").value,start=monthly?`${month}-01`:state.week.fecha_inicio,end=monthly?`${month}-${new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate()}`:state.week.fecha_fin,[entries,movements,weeks,expectedRows]=await Promise.all([supabase.from("registros_horarios").select("*").gte("fecha",start).lte("fecha",end).order("fecha"),supabase.from("movimientos_horas").select("*").gte("fecha",start).lte("fecha",end).order("fecha"),supabase.from("semanas").select("*").gte("fecha_inicio",start).lte("fecha_inicio",end),supabase.from("horas_esperadas").select("*")]);for(const x of[entries,movements,weeks,expectedRows])if(x.error)throw x.error;return{start,end,entries:entries.data,movements:movements.data,weeks:weeks.data,expectedRows:expectedRows.data,monthly}}
async function downloadPdf(){try{const d=await reportData(),individual=$("report-type").value==="individual",selected=Number($("report-employee").value),people=individual?state.mozas.filter(m=>m.id===selected):state.mozas,{jsPDF}=await import("https://cdn.jsdelivr.net/npm/jspdf@2.5.2/+esm"),doc=new jsPDF(),provisional=d.weeks.some(w=>w.estado==="abierta")||(!d.monthly&&state.week.estado==="abierta");let y=18;doc.setTextColor(28,70,53);doc.setFontSize(17);doc.text("CONTROL DE HORAS - MUNSTER",14,y);y+=9;doc.setTextColor(40);doc.setFontSize(11);doc.text(`Periodo: ${fmtDate(d.start)} al ${fmtDate(d.end)}`,14,y);y+=7;doc.text(`Estado: ${provisional?"INFORME PROVISORIO":"INFORME DEFINITIVO"}`,14,y);y+=10;for(const m of people){if(y>260){doc.addPage();y=18}const es=d.entries.filter(e=>e.moza_id===m.id),workedTotal=es.reduce((a,e)=>a+e.minutos_trabajados,0),weekIds=new Set(d.weeks.map(w=>w.id)),expectedTotal=d.expectedRows.filter(x=>x.moza_id===m.id&&weekIds.has(x.semana_id)).reduce((a,x)=>a+x.minutos_esperados,0),returned=Math.abs(d.movements.filter(x=>x.moza_id===m.id&&x.tipo==="devolucion").reduce((a,x)=>a+x.minutos,0));doc.setFont(undefined,"bold");doc.setFontSize(13);doc.text(m.nombre,14,y);y+=6;doc.setFont(undefined,"normal");doc.setFontSize(10);doc.text(`Esperadas: ${fmtMin(expectedTotal)}   Realizadas: ${fmtMin(workedTotal)}   Devueltas: ${fmtMin(returned)}`,14,y);y+=6;for(const e of es){const workedDay=e.estado_dia==="trabajo"||!e.estado_dia,line=workedDay?`${fmtDate(e.fecha)}  ${e.entrada_1.slice(0,5)}-${e.salida_1.slice(0,5)}${e.entrada_2?` / ${e.entrada_2.slice(0,5)}-${e.salida_2.slice(0,5)}`:""}  (${fmtMin(e.minutos_trabajados)})`:`${fmtDate(e.fecha)}  ${String(e.estado_dia).toUpperCase()}`;doc.text(line,18,y);y+=5;if(y>280){doc.addPage();y=18}}y+=7}doc.setFontSize(8);doc.setTextColor(100);doc.text(`Generado el ${new Date().toLocaleString("es-AR")} - ${state.user.email}`,14,290);doc.save(`informe-horas-${d.start}-${d.end}${individual?`-${people[0].nombre}`:"-general"}.pdf`)}catch(e){toast(e.message,true)}}$("download-pdf").onclick=downloadPdf;
async function previewDelete(){const month=$("delete-month").value;if(!month)return toast("Elegí un mes",true);if(month>=today().slice(0,7))return toast("Solo se pueden eliminar meses anteriores",true);const start=`${month}-01`,end=`${month}-${new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate()}`,[weeks,entries]=await Promise.all([supabase.from("semanas").select("*").gte("fecha_inicio",start).lte("fecha_inicio",end),supabase.from("registros_horarios").select("id",{count:"exact"}).gte("fecha",start).lte("fecha",end)]);if(weeks.error||entries.error)return toast((weeks.error||entries.error).message,true);if(weeks.data.some(w=>w.estado==="abierta"))return toast("El mes contiene semanas abiertas",true);const box=$("delete-preview");box.classList.remove("hidden");box.innerHTML=`<div class="delete-summary"><strong>Se eliminarán ${entries.count||0} registros y ${weeks.data.length} semanas.</strong><p>Los saldos pendientes se trasladarán automáticamente.</p><label>Para confirmar escribí ELIMINAR ${month}<input id="delete-confirm" autocomplete="off"></label><button id="delete-final" class="danger-button">Eliminar definitivamente</button></div>`;$("delete-final").onclick=()=>deleteMonth(month,start,end,weeks.data)}$("preview-delete").onclick=previewDelete;
async function deleteMonth(month,start,end,weeks){if($("delete-confirm").value!==`ELIMINAR ${month}`)return toast("La confirmación no coincide",true);if(!confirm("Esta eliminación es definitiva. ¿Continuar?"))return;const nextDate=localIso(new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),1)),weekIds=weeks.map(w=>w.id),balances=[];for(const m of state.mozas){const{data,error}=await supabase.from("movimientos_horas").select("minutos").eq("moza_id",m.id).gte("fecha",start).lte("fecha",end);if(error)return toast(error.message,true);const amount=data.reduce((a,x)=>a+x.minutos,0);if(amount)balances.push({moza_id:m.id,semana_id:null,fecha:nextDate,minutos:amount,tipo:"ajuste",modalidad:"Saldo trasladado",observacion:`Saldo trasladado al eliminar ${month}`,cargado_por:state.user.id})}let result=await supabase.from("movimientos_horas").delete().gte("fecha",start).lte("fecha",end);if(result.error)return toast(result.error.message,true);result=await supabase.from("registros_horarios").delete().gte("fecha",start).lte("fecha",end);if(result.error)return toast(result.error.message,true);if(weekIds.length){result=await supabase.from("horas_esperadas").delete().in("semana_id",weekIds);if(!result.error)result=await supabase.from("semanas").delete().in("id",weekIds);if(result.error)return toast(result.error.message,true)}if(balances.length){result=await supabase.from("movimientos_horas").insert(balances);if(result.error)return toast(result.error.message,true)}$("delete-preview").classList.add("hidden");await load();toast("Mes eliminado y saldos trasladados")}
if(configured){const{data}=await supabase.auth.getSession();if(data.session){state.user=data.session.user;try{await load()}catch(e){showLogin(e.message)}}else showLogin()}else showLogin();
