import {createClient} from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const cfg=window.MUNSTER_CONFIG||{},supabase=createClient(cfg.supabaseUrl,cfg.supabaseKey),$=id=>document.getElementById(id);
let deviceToken=localStorage.getItem("munster_device_token")||"",people=[];
function message(text,bad=false){const el=$("message");el.textContent=text;el.className=`message ${bad?"bad":""}`;setTimeout(()=>el.classList.add("hidden"),3000)}
function clock(){const d=new Date();$("clock-time").textContent=d.toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"});$("clock-date").textContent=d.toLocaleDateString("es-AR",{weekday:"long",day:"2-digit",month:"long"})}clock();setInterval(clock,1000);
const stateLabel=s=>({sin_entrada:"Sin marcar",trabajando:"Trabajando · salida pendiente",en_corte:"Cortado · tramo 1 finalizado",segundo_tramo:"Cortado · tramo 2 en curso",finalizada:"Jornada finalizada"}[s]||"Sin marcar");
async function verifyDevice(){if(!deviceToken)return showSetup();const{data,error}=await supabase.rpc("validar_dispositivo_fichaje",{p_token:deviceToken});if(error||!data){localStorage.removeItem("munster_device_token");deviceToken="";return showSetup()}$("device-setup").classList.add("hidden");$("kiosk").classList.remove("hidden");await loadPeople()}
function showSetup(){$("device-setup").classList.remove("hidden");$("kiosk").classList.add("hidden")}
async function loadPeople(){const{data,error}=await supabase.rpc("listar_mozas_fichaje",{p_token:deviceToken});if(error)return message(error.message,true);people=data||[];$("people").innerHTML=people.map(p=>`<button class="person" data-id="${p.moza_id}"><span class="avatar">${p.nombre[0]}</span><span><h3>${p.nombre}</h3><span class="${p.estado==='trabajando'||p.estado==='segundo_tramo'?'working':p.estado==='en_corte'?'cut':p.estado==='finalizada'?'done':''}">${stateLabel(p.estado)}</span></span></button>`).join("");document.querySelectorAll(".person").forEach(b=>b.onclick=()=>openPerson(Number(b.dataset.id)))}
function openPerson(id){const p=people.find(x=>x.moza_id===id);$("person-id").value=id;$("person-name").textContent=p.nombre;$("pin").value="";const buttons=p.estado==="sin_entrada"?[['entrada','Marcar entrada']]:p.estado==="trabajando"?[['salida','Finalizar jornada'],['salida_corte','Cortado · finalizar tramo 1']]:p.estado==="en_corte"?[['regreso','Cortado · iniciar tramo 2']]:p.estado==="segundo_tramo"?[['salida','Finalizar jornada']]:[];$("actions").innerHTML=buttons.length?buttons.map(([a,l],i)=>`<button type="submit" value="${a}" class="${i?'secondary':''}">${l}</button>`).join(""):`<p>La jornada de hoy ya está completa.</p>`;$("pin-dialog").showModal();$("pin").focus()}
$("device-form").onsubmit=async e=>{e.preventDefault();const code=$("device-code").value.trim(),{data,error}=await supabase.rpc("activar_dispositivo_fichaje",{p_codigo:code});if(error||!data?.ok)return message(data?.mensaje||"Código de computadora incorrecto",true);deviceToken=data.token;localStorage.setItem("munster_device_token",deviceToken);$("device-code").value="";await verifyDevice();message("Computadora habilitada")};
$("pin-form").onsubmit=async e=>{e.preventDefault();const button=e.submitter;if(!button?.value)return;button.disabled=true;const{data,error}=await supabase.rpc("marcar_fichaje",{p_token:deviceToken,p_moza_id:Number($("person-id").value),p_pin:$("pin").value,p_accion:button.value});button.disabled=false;if(error)return message(error.message,true);if(!data?.ok)return message(data?.mensaje||"No se pudo marcar",true);$("pin-dialog").close();message(data.mensaje||"Marcación guardada");await loadPeople()};
$("close-dialog").onclick=()=>$("pin-dialog").close();$("refresh").onclick=loadPeople;verifyDevice();
